### PR TITLE
Upgrade bincode to released version 2 and fix compilation when disabled

### PR DESCRIPTION
**Pull request by markbt**
Currently the build of `plexi-core` fails when the `bincode` feature is disabled:

```
$ cargo check --no-default-features
error[E0004]: non-exhaustive patterns: `Ciphersuite::BincodeEd25519` not covered
   --> plexi_core/src/lib.rs:487:15
    |
487 |         match self.version {
    |               ^^^^^^^^^^^^ pattern `Ciphersuite::BincodeEd25519` not covered
    |
note: `Ciphersuite` defined here
   --> plexi_core/src/lib.rs:50:10
    |
50  | pub enum Ciphersuite {
    |          ^^^^^^^^^^^
51  |     ProtobufEd25519 = 0x0001,
52  |     BincodeEd25519 = 0x0002,
    |     -------------- not covered
    = note: the matched value is of type `Ciphersuite`
```

This is because the bincode arm is compiled out if the feature is disabled.  Instead, keep the match arm and change it to a runtime error if bincode is not enabled.

Bincode 2 has also been released, so we can upgrade to it.  There is a small difference in how the `Decode` and `BorrowDecode` traits are defined which we must adapt to.

### CODE REVIEW

**Review by RageKnify — APPROVED** [review]

**Comment by thibmeu** [comment]
@markbt Thank you for the commit. Overall looks ok.

The builds have been fixed to work with rust 1.86 in #22. This is required by some of the dependencies you are updating. You should be able to rebase on `main` to fix them.

**Comment by markbt** [comment]
I missed the notification for your reply, sorry about that.  I've rebased onto `main`.
